SHELF_FLOOR_HEIGHT = 0.5
SHELF_FLOORS = 3
SHELF_WIDTH = 1
SHELF_THICKNESS = 0.016
SHELF_DEPTH = 0.4
SHELF_HEIGHT = SHELF_FLOORS * SHELF_FLOOR_HEIGHT + SHELF_THICKNESS

ROBOT_DISTANCE_SHELF = 4

BRICK_WIDTH = 0.01
BRICK_HEIGHT = 0.3
BRICK_LENGTH = 0.3

CHAIN_N = 4
CHAIN_RADIUS = 0.05
CHAIN_LENGTH = 0.1

SOUP_CAN_HEIGHT = 0.1

RUBIKS_CUBE_HEIGHT = 0.05

SHELVE_BODY_NAME = 'shelve_body'
